OpenMDAO/Aviary

aviary/interface/methods_for_level2.py
aviary/mission/flops_based/phases/cruise_phase.py
aviary/mission/flops_based/phases/energy_phase.py
aviary/mission/flops_based/phases/phase_utils.py
aviary/mission/flops_based/phases/simple_energy_phase.py

Slightly refactored the time options logic for the simple mission to address #9
- Resolves #9
None
None

Resolve unnecessary warning

---

aviary/api.py
aviary/examples/external_subsystems/OAS_weight/test_OAS_wing_weight_builder.py
aviary/examples/external_subsystems/battery/test_battery_builder.py
aviary/subsystems/test/subsystem_tester.py

Simplified the dependency check when importing subsystem builders
- Resolves #
None
None

Improved skip logic for missing dependencies

---

README.md

This is a tiny PR that makes a line at the top of the README where first times users can easily find a link to the docs.
None
None

making easily visible doc button

---

aviary/docs/getting_started/onboarding_ext_subsystem.ipynb

Summary of PR.
- Resolves #
None
None

Editorial modifications to this file for readabiliy.

---

.github/install_env_from_github.sh
aviary/docs/getting_started/onboarding_ext_subsystem.ipynb
aviary/examples/external_subsystems/battery/model/reg_thevenin_interp_group.py
setup.py

This removes the dependency on external battery repos.

Added battery data for example

---

.github/workflows/test_workflow.yml
.github/workflows/test_workflow_no_dev_install.yml
setup.py

Hotfix for failing CI.
- Resolves #
None
None

Updating actions versions

---

aviary/interface/methods_for_level2.py
aviary/validation_cases/benchmark_tests/test_bench_FwFm.py
aviary/validation_cases/benchmark_utils.py

Fixed a couple of MPI issues including a hang.  Also, added an MPI test to prevent any new issues from appearing.
- Resolves #138 
None
None

Fixed a couple of MPI issues including a hang.

---

aviary/examples/test/test_all_examples.py

Summary of PR.
- Resolves #
None
None

increased max allowable time for subprocess

---

.github/workflows/notify_teams.yml

removed redundant `github.event_name` check
added reviewers to sent information
added conversion to and from draft logic
- Resolves #
None
None

Added reviewers when PR is opened

---

aviary/docs/user_guide/examples_of_the_same_mission_at_different_UI_levels.ipynb
aviary/interface/reports.py

Fixes a couple of bugs that have cropped up in recent updates:
1. Fixed a bug that caused several input reports (e.g., the n2) not to show up in the dashboard anymore.
- (This is likely a bug in openmdao. Added a workaround for it.) 
2. Made the new mission summary work under MPI.
- Resolves #
None
None

Fix some report regressions.

---

aviary/visualization/dashboard.py

Added mission summary report to dashboard.
Also updated formatting to be pep8.
- Resolves #155 
None
None

Added mission summary report to dashboard

---

.github/workflows/notify_teams.yml

Summary of PR.
- Resolves #
None
None

fixed path

---

.github/ISSUE_TEMPLATE/doc_request.yml

Tiny PR to add an extra form in the issue backlog for documentation enhancement requests.
None
None

adding additional form for issues

---

aviary/models/large_turboprop_freighter/large_turboprop_freighter.dat

Some cleanup on the comments in the turboprop freighter model

Turboprop model cleanup

---

aviary/interface/methods_for_level2.py

Adjusted settings to improve readability
- Resolves #
None
None

tweaked driver display settings to improve readability

---

aviary/interface/methods_for_level2.py
aviary/utils/fortran_to_aviary.py
aviary/utils/functions.py
aviary/utils/process_input_decks.py
aviary/variable_info/variable_meta_data.py
aviary/variable_info/variables.py

This issue was found by @cmbenne3 and will support his off-design work
- Resolves #
None
None

Made problem_type an official setting in preparation for off-design work

---

aviary/docs/_toc.yml
aviary/docs/getting_started/installation.md
aviary/docs/misc_resources/modeling_exercise.md

Add the modeling exercise used in the usability study.
Have users install and run Aviary, modify a run script, and report out results in the usability study.
- Resolves #
None
None

Added first version of modeling exercise for usability study

---

aviary/mission/gasp_based/ode/climb_ode.py
aviary/mission/gasp_based/ode/descent_ode.py
aviary/mission/gasp_based/ode/flight_path_ode.py

using auto_order to simplify logic
- Resolves #
None
None

using auto_order

---

aviary/interface/methods_for_level2.py
aviary/utils/test_utils/variable_test.py
aviary/variable_info/test/test_var_structure.py

Refactor the assert that checks whether the variable hierarchy is in proper alphabetical order so that it is cleaner and works with arbitrary depth.
- Resolves #
None
None

Refactor assert that checks whether the variable hierarchy is in proper alphabetical order.

---

aviary/subsystems/propulsion/test/test_propeller_performance.py

This PR adds unit test for the new class TipSpeedLimit.
- Resolves #
None
None

Add Tip speed limit unit test

---

aviary/examples/external_subsystems/engine_NPSS/define_simple_engine_problem.py
aviary/interface/test/test_timeseries_report.py
aviary/validation_cases/benchmark_tests/test_FLOPS_based_sizing_N3CC.py

Fixes a couple of benchmarks that have been failing on the nightly server.
- Resolves #322
None
None

Fix for a couple of recently failing benchmarks.

---

aviary/examples/level2_shooting_traj.py
aviary/interface/methods_for_level1.py
aviary/interface/methods_for_level2.py
aviary/interface/test/test_height_energy_mission.py
aviary/interface/test/test_linkage_logic.py

Making the problem status an attribute instead of a function return.
- Resolves #250
None
None

Changed problem return failure to an attribute

---

aviary/docs/misc_resources/comparison_to_flops.md
aviary/docs/misc_resources/glossary.md
aviary/docs/user_guide/propulsion.ipynb
aviary/examples/external_subsystems/battery/run_multiphase_mission.py
aviary/examples/external_subsystems/engine_NPSS/table_engine_builder.py
aviary/interface/download_models.py
aviary/interface/test/test_cmd_entry_points.py
aviary/interface/test/test_download_models.py
aviary/interface/test/test_interface_bugs.py
aviary/mission/flight_phase_builder.py
aviary/subsystems/aerodynamics/flops_based/skin_friction.py
aviary/subsystems/aerodynamics/gasp_based/test/test_table_based.py
aviary/subsystems/mass/flops_based/landing_gear.py
aviary/subsystems/mass/flops_based/misc_engine.py
aviary/subsystems/propulsion/utils.py
aviary/utils/functions.py
aviary/utils/preprocessors.py
aviary/utils/process_input_decks.py
aviary/variable_info/variable_meta_data.py
setup.py

Renaming any use of `multi-engine` to use homogenous or heterogeneous as appropriate.
- Resolves #296 
- Resolves #344
None
None

Multi-engine renaming

---

aviary/subsystems/aerodynamics/gasp_based/flaps_model/Cl_max.py
aviary/subsystems/aerodynamics/gasp_based/flaps_model/flaps_model.py
aviary/subsystems/aerodynamics/gasp_based/flaps_model/test/test_Clmax.py
aviary/subsystems/aerodynamics/gasp_based/flaps_model/test/test_flaps_group.py
aviary/subsystems/aerodynamics/gasp_based/gaspaero.py
aviary/subsystems/aerodynamics/gasp_based/premission_aero.py
aviary/subsystems/aerodynamics/gasp_based/test/test_gaspaero.py
aviary/variable_info/variable_meta_data.py
aviary/variable_info/variables.py

Replaced "nu" with Dynamic.Mission.KINEMATIC_VELOCITY
- Resolves #
None
None

adding kinematic viscosity as a dynamic variable

---

aviary/subsystems/aerodynamics/gasp_based/test/test_interference.py
aviary/subsystems/energy/battery_builder.py
aviary/subsystems/propulsion/gearbox/gearbox_builder.py
aviary/subsystems/propulsion/gearbox/model/gearbox_mission.py
aviary/subsystems/propulsion/gearbox/test/test_gearbox.py
aviary/subsystems/propulsion/motor/model/motor_mission.py
aviary/utils/preprocessors.py
aviary/validation_cases/benchmark_tests/test_battery_in_a_mission.py
aviary/variable_info/variable_meta_data.py
aviary/variable_info/variables.py

Pushing fixes for tests that occurred due to intentional changes for 0.9.6 being overwritten by changes to main
- Resolves #
None
None

merge fixes

---

aviary/subsystems/propulsion/propeller/hamilton_standard.py
aviary/subsystems/propulsion/propeller/propeller_performance.py
aviary/subsystems/propulsion/test/test_propeller_performance.py
aviary/variable_info/test/test_var_structure.py
aviary/variable_info/variable_meta_data.py
aviary/variable_info/variables.py

merge 0.9.6.dev with main
- Resolves #
None
None

merge with main

---

aviary/validation_cases/benchmark_tests/test_bench_multiengine.py

Alternate fix to #618 which does not hard-code specific variable fixes
Temporary patch for issue #621 until that can be properly resolved
- Resolves #
None
None

added missing vars to test

---

.github/actions/prepare_environment/action.yml
.github/workflows/test_workflow_no_dev_install.yml

Summary of PR.
- Resolves #
None
None

Addressing Deprecation notice: v3 of the artifact actions

---

.github/workflows/publish-image.yml
Dockerfile.arm

Added an ARM image definition file and a job to the 'publish-image` workflow to build and publish the ARM image along with the previous X86 image.  This new image should be more performant on ARM hosts like Apple's Mx-based Macs.
Note that this image takes much longer to build because there is no pre-built version of VTK for ARM, so it's built from source along with OpenVSP which requires it.  An optimization would be to build and keep these packages elsewhere and avoid building them here, but since releases are not that frequent I think it doesn't hurt to keep the build process documented here.
- Resolves #
None
None

Added an ARM image

---

aviary/mission/gasp_based/ode/unsteady_solved/test/test_unsteady_flight_conditions.py
aviary/mission/gasp_based/ode/unsteady_solved/unsteady_solved_flight_conditions.py

Summary of PR.
- Resolves #
None
None

Fix for CI regression in detailed landing.

---

aviary/subsystems/aerodynamics/aerodynamics_builder.py
aviary/subsystems/aerodynamics/flops_based/drag.py
aviary/subsystems/aerodynamics/flops_based/test/test_drag.py
aviary/subsystems/aerodynamics/gasp_based/table_based.py
aviary/subsystems/aerodynamics/gasp_based/test/test_solved_aero_group.py

Added a component to scale the tabular drag by the super/subsonic factor.
- Resolves #414
None
None

Added a component to scale the tabular drag by the super/subsonic factor.
