aviary/docs/getting_started/onboarding_ext_subsystem.ipynb, aviary/docs/user_guide/battery_subsystem_example.md, aviary/examples/external_subsystems/battery/battery_variable_meta_data.py, aviary/examples/external_subsystems/battery/battery_variables.py, aviary/examples/external_subsystems/battery/model/battery_mission.py, aviary/examples/external_subsystems/battery/model/reg_thevenin_interp_group.py, aviary/examples/external_subsystems/battery/run_cruise.py, aviary/examples/external_subsystems/battery/run_multiphase_mission.py, aviary/examples/external_subsystems/battery/test_battery_builder.py
This is a tiny PR that removes the flag for battery cell type in the battery external subsystem example. There was only one type of battery so the flag was never used.
- NA
None
None
=> Removing battery cell type since it is no longer used

aviary/examples/external_subsystems/OAS_weight/test_OAS_wing_weight_builder.py, aviary/examples/external_subsystems/battery/test_battery_builder.py
Modified tests of external subsystems to skip if dependencies aren't installed.
This prevents test failures for users with only core Aviary installed
- Resolves #
None
None
=> Skipping tests for external subsystems with missing dependencies

aviary/docs/getting_started/onboarding_ext_subsystem.ipynb, aviary/docs/getting_started/onboarding_level2.ipynb, aviary/interface/methods_for_level2.py
- Finished writing the OAS example in `onboarding_ext_subsystem.ipynb`. Have to use `run_model` instead of `run_driver` because OAS runtime exceeded the maximum allowed. 
- In `methods_for_level2.py`, the variable `final_range_nmi` is commented out because it is never used and will cause error when `run_model`. 
- In `onboarding_level2.ipynb`, replaced `bench2_history.db` by `aviary_history.db`.
- Resolves #
None
None
=> Onboarding external subsystem update

aviary/docs/getting_started/onboarding_level1.ipynb, aviary/docs/getting_started/onboarding_level2.ipynb, aviary/docs/intro.md, aviary/docs/user_guide/aviary_commands.ipynb, aviary/interface/methods_for_level1.py, aviary/interface/methods_for_level2.py, aviary/interface/test/test_cmd_entry_points.py
Minor changes to:
- doc intro page for clarity based on user feedback
- combining `mission_method` and `mission_origin` into `mission_method`
- Resolves #12 
- Resolves #21
None
None
=> Minor tweaks to docs and naming

.github/workflows/test_workflow_no_dev_install.yml, setup.py
1. The setup.py file package_data variables did not include the directory with the CSS file for the dashboard. Added
3. The no dev install workflow was testing the code in the repo, not the package that was installed into site-packages. Modified the github workflow
- Resolves #39 and #27 
None
None
=> Add CSS file for dashboard to package_data. Also mod the no dev install workflow to test package

aviary/examples/test/test_all_examples.py
Correctly handle `ImportError`, relevant when `pip install .` without `[all]`.
- Resolves #
None
None
=> fix for run all examples test

aviary/mission/flops_based/ode/landing_ode.py, aviary/mission/flops_based/ode/takeoff_ode.py, aviary/mission/flops_based/phases/detailed_takeoff_phases.py, aviary/mission/gasp_based/ode/accel_ode.py, aviary/mission/gasp_based/ode/ascent_ode.py, aviary/mission/gasp_based/ode/breguet_cruise_ode.py, aviary/mission/gasp_based/ode/climb_ode.py, aviary/mission/gasp_based/ode/descent_ode.py, aviary/mission/gasp_based/ode/flight_path_ode.py, aviary/mission/gasp_based/ode/groundroll_ode.py, aviary/mission/gasp_based/ode/rotation_ode.py
Summary of PR.
- Resolves #
None
None
=> Renamed EOMs in ODEs for clarity

aviary/docs/getting_started/onboarding_level2.ipynb, aviary/interface/methods_for_level2.py, aviary/validation_cases/benchmark_tests/test_bench_FwGm.py, aviary/validation_cases/benchmark_tests/test_subsystems_within_a_mission.py
Prior to this change, the level 2 interface handled setting the model's input defaults by a call to a utility function right before setup. Since at this point, it isn't possible to figure out what inputs are in the model, we called set_input_defaults on everything in the aircraft metadata. Unfortunately, if you promote an input that isn't in the model, OpenMDAO raises an error. Our original workaround was to create the "input_sink" component, which contained almost every variable in the metadata dictionary. This approach caused other problems that we have gradually discovered...
This PR is a re-implementation, where we delay calling set_input_defaults until the top group's configure method. At this point, we know all of our subsystem's inputs and can query them, so we no longer need the …
=> Refactor level2 to eliminate the input_sink and set all input defaults in the top group's configure method.

aviary/variable_info/variable_meta_data.py
Thanks to #131, I noticed that some of the metadata entries were missing spaces at the line breaks.
This PR fixes the missing spaces at line breaks in descriptions and makes the location of the space and the indentation of multiline descriptions consistent.
- Resolves #
None
None
=> Fixed missing/inconsistent spaces at line breaks in desc

aviary/docs/developer_guide/coding_standards.md, aviary/docs/user_guide/troubleshooting.md, aviary/interface/methods_for_level1.py, aviary/interface/methods_for_level2.py, aviary/interface/test/test_basic_report.py, aviary/interface/test/test_height_energy_mission.py, aviary/interface/test/test_interface_bugs.py, aviary/interface/test/test_linkage_logic.py, aviary/subsystems/propulsion/test/test_custom_engine_model.py, aviary/validation_cases/benchmark_tests/test_0_iters.py, aviary/validation_cases/benchmark_tests/test_bench_FwFm.py, aviary/validation_cases/benchmark_tests/test_bench_FwGm.py, aviary/validation_cases/benchmark_tests/test_bench_GwFm.py, aviary/validation_cases/benchmark_tests/test_bench_GwGm.py, aviary/validation_cases/benchmark_tests/test_subsystems_within_a_mission.py
adjusted print level of driver based on verbosity
made BRIEF the default of add_driver and run_aviary
switched tests to use QUIET
(Examples still use BRIEF)
This makes warnings and errors easier to find and debug
- Resolves #
None
None
=> Using verbosity settings to control print level

.github/workflows/notify_teams.yml
Sending review information when a review is submitted
- Resolves #
None
None
=> Adding notification for PR reviews

.github/workflows/notify_teams.yml
Reverts OpenMDAO/Aviary#185
pull-request-review runs in the forked repository, not the main repository, so it does not have access to the necessary secrets.
We could setup a workaround if desired.
https://stackoverflow.com/questions/67247752/how-to-use-secret-in-pull-request-review-similar-to-pull-request-target
=> Revert "Adding notification for PR reviews"

aviary/examples/external_subsystems/engine_NPSS/define_simple_engine_problem.py, aviary/examples/external_subsystems/engine_NPSS/test_NPSS_builder.py
Renamed the NPSS builder test case so that it runs with the other benchmark tests via `testflo --testmatch=bench_test*` (if NPSS is available)
- renamed the file `benchmark_NPSS_builder.py` to `test_NPSS_builder.py`
- renamed the `BenchAviaryNPSS` test case to `AviaryNPSSTestCase`
- renamed the `test_bench_aviary_NPSS` test function to `bench_test_aviary_NPSS`
Also:
- added a call to `check_and_preprocess_inputs` which seems to be required now
- Resolves #
None
None
=> Renamed NPSS builder test

aviary/interface/test/test_height_energy_mission.py
This test runs through the level 1 interface, so all the problems use the same name. When we clear the problem names, the report registry is not getting cleared out.  It probably should be cleared out by OpenMDAO when we call `_clear_problem_names`, but such is the risk of using private functions. Until that is fixed in openmdao, we can manually make the call to `clear_reports` in our test setup.
Note: if you run with testflo and have enough procs, you probably never saw this error.
- Resolves #
None
None
=> Fix for some intermittent failures due to active reports.

aviary/interface/methods_for_level2.py, aviary/interface/reports.py
1. We were getting an exception when configuring TACS, which has distributed variables. The ultimate bug is on the openmdao side, but we are able to sidestep it in Aviary by telling list_outputs not to gather the input values, since we were not using them anyway.
2. We were seeing an exception on ranks 1+ when printing the timeseries report. This was fixed by letting the non-zero ranks exit after the last collective call, so that they didn't try to interact with an empty dictionary.
- Resolves #
None
None
=> A couple more fixes for MPI execution.

aviary/examples/reserve_missions/run_2dof_reserve_mission_fixedrange.py, aviary/examples/reserve_missions/run_2dof_reserve_mission_fixedtime.py, aviary/examples/reserve_missions/run_2dof_reserve_mission_multiphase.py, aviary/examples/reserve_missions/run_reserve_mission_fixedrange.py, aviary/examples/reserve_missions/run_reserve_mission_fixedtime.py, aviary/examples/reserve_missions/run_reserve_mission_multiphase.py
I think this should fix the nightly benchmark failures.
The error was caused by trying to read an SQL file while it was being written.
I've seen this happen before when the .db file has the same name.
By giving unique names we should sidestep this issue.
- Resolves #
None
None
=> Added db filenames to run examples

aviary/interface/methods_for_level2.py, aviary/mission/gasp_based/ode/time_integration_base_classes.py, aviary/mission/gasp_based/phases/time_integration_traj.py, aviary/validation_cases/benchmark_tests/test_bench_GwGm.py
Adding intermediate state outputs to SGM trajectories, this allows users to specify states to be output from a phase that is not the final one.
Also included is a prototype of the ability to output non state variables mid trajectory as well.
This will eventually be used with #245 to allow users to run the estimation once in pre-mission, and then use the actual descent fuel from the trajectory for the new guess of descent fuel for the next iteration
- Resolves #
None
None
=> Added intermediate state output to SGM trajectories

aviary/examples/test/test_all_examples.py
After a recent update, the following test is failing due to a timeout:
```
/mdao/u/swryan/benchmark/runner/repos/Aviary/Aviary/aviary/examples/test/test_all_examples.py:RunScriptTest.test_run_scripts (script='run_2dof_reserve_mission_multiphase.py') ... FAIL (811:30:40.47, 308 MB)
Traceback (most recent call last):
File "/mdao/u/swryan/benchmark/runner/repos/Aviary/Aviary/aviary/examples/test/test_all_examples.py", line 110, in test_run_scripts
self.run_script(script_path)
File "/mdao/u/swryan/benchmark/runner/repos/Aviary/Aviary/aviary/examples/test/test_all_examples.py", line 91, in run_script
proc.wait(timeout=max_allowable_time)
File "/mdao/u/swryan/.conda/envs/Aviary_20240420-000006/lib/python3.12/subprocess.py", line 1264, in wait
return self._wait(timeout=timeout) …
```
=> Increased the timeout on `test_run_scripts`

aviary/docs/developer_guide/coding_standards.md, aviary/examples/external_subsystems/battery/model/battery_mission.py, aviary/mission/gasp_based/ode/unsteady_solved/unsteady_control_iter_group.py, aviary/subsystems/aerodynamics/gasp_based/flaps_model/__init__.py, aviary/subsystems/mass/gasp_based/fixed.py
In some Aviary source files, some import statements for Aviary modules are relative. Some of these source files are runnable as standalone scripts - which typically do not work well with relative import statements. For this reason, I converted all relative paths to absolute paths. I also added a guideline in developer guide.
- Resolves #
None
None
=> Import statement using absolute path

aviary/docs/examples/intro.md, aviary/docs/user_guide/drawing_and_running_simple_missions.md, aviary/interface/graphical_input.py
Add note in the GUI and in another doc location that `black` helps the output be more readable.
Made the `done` button more explanative: `Output phase_info object`
- Resolves #
None
None
=> Clarify draw_mission outputted dict format

aviary/docs/getting_started/onboarding_ext_subsystem.ipynb, aviary/examples/external_subsystems/battery/battery_builder.py, aviary/examples/external_subsystems/battery/run_cruise.py, aviary/examples/external_subsystems/battery/run_multiphase_mission.py, aviary/examples/external_subsystems/engine_NPSS/define_simple_engine_problem.py, aviary/interface/methods_for_level2.py, aviary/utils/process_input_decks.py
When adding external subsystem variables (e.g. `Aircraft.Battery.CURRENT_MAX`) to input deck (.csv file), these variables are not read in. This PR fixes this bug.
Changed the initial value and upper bound of `Aircraft.Battery.Cell.DISCHARGE_RATE` to avoid an unnecessary warning message.
- Resolves [deprecated issue #423](https://github.com/OpenMDAO/Aviary_deprecated/issues/423)
- Check  [deprecated issue #319](https://github.com/OpenMDAO/Aviary_deprecated/issues/319) too
None
None
=> Read csv extended

aviary/interface/methods_for_level1.py, aviary/interface/test/test_cmd_entry_points.py, aviary/utils/functions.py
phase_info was being treated as a dict when it was passed to run_aviary
added a preprocessor to run_level_1 that extracts phase_info and phase_info_parameterization (if present) from the file path that is specified through the CLI and then passes them to run_aviary.
Also prevented the FileNotFoundError raised in get_model from causing get_path to fail prematurely.
- Resolves #
None
None
=> fixed bugs related to specifying phase_info from the CLI

aviary/subsystems/aerodynamics/flops_based/takeoff_aero_group.py
The FLOPS-based tabular low-speed takeoff aero group includes landing gear drag in the net drag coefficient equation but does not have an option to disable it, meaning landing gear drag is added to all segments of takeoff if a value is provided by the user. 
A gear retraction option is added to enable or disable this effect from the user-provided aerodynamics info. Note that this solution is different from legacy codes, which use cosinusoidal equations to gradually reduce drag. A more permanent solution to this issue would be to gradually decrease drag over a specified duration.
- Resolves #275 
None
None
=> Add option to tabular takeoff aero so landing gear drag can be excluded

aviary/subsystems/aerodynamics/gasp_based/gaspaero.py
In `LowSpeedAero` (GASP based), alpha is NOT an output even though the code indicates that `output_alpha` is `True`. This was a comment and is replaced by a warning message. Currently, this option (`output_alpha == True`) is not used. If it is needed, GASP has a subroutine to compute alpha. We can implement it in Aviary.
- Resolves [deprecated Aviary #343](https://github.com/OpenMDAO/Aviary_deprecated/issues/343)
None
None
=> In LowSpeedAero, alpha is NOT an output

aviary/utils/fortran_to_aviary.py, aviary/variable_info/enums.py
changed `set` to `values`
PR300 was merged before the last commit was pushed
- Resolves #
None
None
=> patch for PR 300

aviary/docs/getting_started/onboarding_level2.ipynb, aviary/docs/user_guide/FLOPS_based_detailed_takeoff_and_landing.ipynb, aviary/docs/user_guide/drawing_and_running_simple_missions.ipynb, aviary/docs/user_guide/hamilton_standard.ipynb, aviary/docs/user_guide/input_files.ipynb, aviary/docs/user_guide/step_by_step_external_guide.ipynb, aviary/docs/user_guide/variable_metadata.ipynb
some of the `# Testing Cell`s were missing their `remove-cell` tag
- Resolves #
None
None
=> Fixing some missing tags

.github/actions/prepare_environment/action.yml, .github/workflows/test_benchmarks.yml, .github/workflows/test_workflow_dev_deps.yml, .github/workflows/test_workflow_no_dev_install.yml
Separated testing of 'dev' versions of OpenMDAO/Dymos from the main test workflow.
- removed the `dev` job from the test matrix in `test_workflow`
- created a new `test_workflow_dev_deps`, which will run the `dev` job on a weekly basis
- this workflow will run via cron on Tuesdays at 4:00AM GMT (Midnight ET)
- this workflow tests with pre-release OpenMDAO/Dymos and the latest release of pyoptsparse
- this workflow will send an e-mail if the tests fail
- added the option to test with the latest release version of pyoptsparse to `action.yml`
- added testflo `--timeout` argument to all workflows to guard against lockups, etc.
- changed the name of "no dev" workflow, since it had the same name as the test workflow
- Resolves #454
None
None
=> Separated testing of 'dev' versions of dependencies from the main test workflow

aviary/interface/methods_for_level2.py, aviary/utils/process_input_decks.py, aviary/validation_cases/benchmark_tests/test_bench_multiengine.py
Fix for the failing multi-engine tests. They had previously failed during initial condition preparations because, when there are multiple engine models, the thrust is found in the engine builders, not in the aviary inputs. With this change, the thrust from all engines is used to later guess at gamma.
- Resolves #
None
None
=> Fix for failing tests.

aviary/subsystems/aerodynamics/flops_based/test/test_drag.py
One of the unit tests in `test_drag.py` has an unreasonable output. It was because one required input was missing: `Dynamic.Mission.DYNAMIC_PRESSURE`. This PR adds this variable.
- Resolves #
None
None
=> add missing input Dynamic.Mission.DYNAMIC_PRESSURE to get reasonable test output

.github/workflows/test_workflow_dev_deps.yml
This fixes an error in PR #455.  
The second checkout of the `.github/actions` directory was meant to precede the attempt to use the `send_email` action.
It has also been made to execute only `if: failure()` since it is not needed for a nominal test run.
- Resolves #
None
None
=> Corrected error in `test_workflow_dev_deps`

.github/workflows/test_workflow_dev_deps.yml
This is a follow up to #467, which fixed the sending of an e-mail, but that e-mail did not contain any useful information.
This adds the name of the workflow and a link to the failed run.
- Resolves #
None
None
=> Add useful information to e-mail when "dev_deps" workflow fails

.github/workflows/test_benchmarks.yml, .github/workflows/test_docs.yml, .github/workflows/test_workflow.yml, .github/workflows/test_workflow_dev_deps.yml, .github/workflows/test_workflow_no_dev_install.yml, setup.py
Point CI to the previous openmdao release until we have things fixed. Also, keep numpy less than 2.
- Resolves #
None
None
=> Point CI to the previous openmdao release until we have things fixed. Also, keep numpy less than 2.

aviary/subsystems/aerodynamics/aerodynamics_builder.py, aviary/subsystems/aerodynamics/flops_based/test/test_solved_aero_group.py, aviary/subsystems/aerodynamics/flops_based/test/test_tabular_aero_group.py
Fixed bug where wing area wasn't being promoted out of the mission when using tabular "FLOPS" aero.
- Resolves #551
None
None
=> Fixed bug where wing area wasn't being promoted out of the mission when using tabular "FLOPS" aero.

aviary/subsystems/propulsion/propeller/hamilton_standard.py, aviary/subsystems/propulsion/propeller/propeller_performance.py, aviary/subsystems/propulsion/test/test_propeller_performance.py
Currently, there are two uses of `min()` function in `InstallLoss` class. That results in the discontinuity of partial derivatives. These two min() functions are replaced by a smoothed minimum function using the log-sum-exp trick. The new function along with its derivative are added to `aviary/subsystems/propulsion/propeller/propeller_performance.py` because it is not used anywhere else. The smoothing factor `alpha` is set to `100.0`. It is tested that this factor should be limited to between 75 and 275. Otherwise, a few unit tests will fail.
`aviary/subsystems/propulsion/propeller/hamilton_standard.py` is updated at a few places to avoid a few `numpy` warnings and to fix a bug.
- Resolves #
None
None
=> Smoothen minimum function in propeller performance

aviary/examples/external_subsystems/engine_NPSS/NPSS_Model/DesignEngineGroup.py, aviary/mission/flops_based/ode/landing_eom.py, aviary/mission/flops_based/ode/landing_ode.py, aviary/mission/flops_based/ode/takeoff_ode.py, aviary/subsystems/aerodynamics/flops_based/solved_alpha_group.py, aviary/subsystems/aerodynamics/flops_based/takeoff_aero_group.py, aviary/subsystems/aerodynamics/gasp_based/table_based.py, aviary/subsystems/energy/battery_builder.py, aviary/subsystems/propulsion/turboprop_model.py, aviary/utils/test_utils/default_subsystems.py
`ExecComps` that are sized to `num_nodes` should have the parameter `has_diag_partials=True` so OpenMDAO can take advantage of sparsity. This PR addresses this issue.
Couple of `ExecComps` are not updated because I am changing them to classes.
Added docstrings for `aviary/utils/test_utils/default_subsystems.py`.
- Resolves #480 
None
None
=> Adding has_diag_partials to ExecComps

aviary/visualization/dashboard.py
OpenMDAO recently changed the directory structure of the reports it generates. The Aviary dashboard gets its inputs from files in the reports directory. The code needed to be updated to look in the correct location. 
Also made greater use of the pathlib library when creating paths. 
Changed one tab so that it reports any problems in its generation in the tab rather than a warning to the command line.
- Resolves #586 
Dashboard will not work if the reports are still in the old location of the reports in previous versions of OpenMDAO.
None
=> Changing were dashboard looks for input files based on recent changes in how OpenMDAO saves reports

aviary/utils/doctape.py, aviary/utils/test/test_doctape.py
allowing anything with a string representation to be passed as the name
- Resolves #
None
None
=> Doctape updates

.github/workflows/publish-image.yml, Dockerfile
`Dockerfile` contains instructions to build a container image with a Python environment for working with Aviary and some affiliated packages (MPhys, OpenAeroStruct and OpenVSP).
The GitHub workflow will build an image when triggered, either manually or by a `release` event.  The image will be tagged according to the current version tag/commit in the repository.
To make use of an image file, the end user would install either `docker` or `podman` and issue the following commands:
```
podman pull ghcr.io/OpenMDAO/Aviary:v0.9.8-xxx
podman run --name aviary -v ~/work:/home/omdao/work ghcr.io/OpenMDAO/Aviary:v0.9.8-xxx &
podman exec -it aviary /bin/bash
```
The `-v` option maps a work directory on the host to a work directory inside the container.
For further information see …
=> Added image definition and a workflow to publish the image

aviary/examples/test/test_all_examples.py
This splits the run_examples tests into separate tests for each example, which will improve the testflo runtime for the tests, and allow us to find and address specific issues.
- Resolves #
None
None
=> Split run_examples into separate tests.

aviary/subsystems/propulsion/engine_deck.py, aviary/subsystems/propulsion/engine_model.py, aviary/subsystems/propulsion/propulsion_builder.py, aviary/subsystems/propulsion/propulsion_mission.py, aviary/subsystems/propulsion/propulsion_premission.py
Adds `**kwargs` support to `build_mission()`, `build_premission()` so `subsystem_options` in `phase_info` can be passed down into individual engines
- Resolves #
None
None
=> Added subsystems_options combability to propulsion builder

aviary/interface/test/test_phase_info.py, aviary/mission/flops_based/phases/test/test_time_integration_phases.py, aviary/subsystems/aerodynamics/flops_based/test/test_tabular_aero_group.py, aviary/subsystems/aerodynamics/test/test_external_mission_aero.py, aviary/subsystems/test/test_external_subsystem_bus.py
This PR is a solution to issue #503 "Stop generation of reports during testing".
I added use_tempdir wherever needed to avoid output directories during testflo runs
- Resolves #503 
None
None
=> added use_tempdir to unit tests

aviary/subsystems/mass/flops_based/landing_gear.py
This PR moves the y_eng_fore calculation to within the `if_num_wing_eng > 0:` if statement. This calculation is only valid if the if statement is true. I verified that `aviary/subsystems/mass/flops_based/test/test_landing_gear.py` ran successfully with this change. 
- Resolves #699. I verified the test case stated in the issue runs without error. 
None
None
=> move y_eng_fore calculation inside if statement in landing_gear.py

.github/workflows/test_benchmarks.yml, .github/workflows/test_docs.yml, .github/workflows/test_workflow.yml, .github/workflows/test_workflow_no_dev_install.yml, aviary/examples/run_detailed_takeoff_in_level2.py, aviary/examples/test/test_level2_shooting_traj.py, aviary/interface/methods_for_level2.py, aviary/interface/test/test_height_energy_mission.py, aviary/mission/flight_phase_builder.py, aviary/mission/flops_based/phases/groundroll_phase.py, aviary/mission/gasp_based/phases/accel_phase.py, aviary/mission/gasp_based/phases/climb_phase.py, aviary/mission/gasp_based/phases/descent_phase.py, aviary/mission/gasp_based/phases/twodof_phase.py, aviary/mission/two_dof_problem_configurator.py, aviary/utils/functions.py, aviary/validation_cases/benchmark_tests/test_bench_GwGm.py, aviary/validation_cases/benchmark_tests/test_subsystems_within_a_mission.py, aviary/variable_info/variable_meta_data.py, aviary/variable_info/variables.py
New OpenMDAO and dymos commits broke some of our Aviary tests and functionality because of stricter checking:
1. The phase add_timeseries now raises an error if the variable does not exist. This PR removes some extra calls to add_timeseries for variables that weren't in the phase. Probably cut-and-pasted from elsewhere.
2. OpenMDAO has lost support for setting and getting variable paths that are hybrids of lower subsystem relative vars. It was never truly supported, but used to work. For example:
absolute: traj.phases.ascent.param_comp.t_initial
hybrid: traj.ascent.t_initial
promoted: mission:takeoff:ascent_t_initial
In this case, we used to be able to use the hybrid name at the prob level, but now, it is only available as a local relative promoted name in a deeper subsystem context. To …
=> Some fixes for the recent CI regression due to latest OpenMDAO release.

aviary/interface/methods_for_level2.py, aviary/interface/test/test_interface_bugs.py
Adding flag to optionally force phase group to be serial when calling `add_phases`. Defaults to `True` (phases group is a ParallelGroup), which is already the dymos default.
- Resolves #682
None
None
=> Adding parallel phase flag to `add_phases`

aviary/interface/reports.py, aviary/interface/test/test_reports.py
Fixed a bug where the input_check_report didn't support custom metadata variables.
- Resolves #
None
None
=> Fixed a bug where the new input_check_report raises an exception when used with a custom metadata dict.

aviary/interface/test/test_reports.py, aviary/validation_cases/benchmark_tests/test_subsystems_within_a_mission.py
1. The case in test_reports has some trouble running, but it is a degenerate case that creates a specific condition for a report. It just needs to final_setup.
2.  The dymos bug that broke the initial value for controls has been fixed.
- Resolves #
None
None
=> Fix for 2 test failures on main.

aviary/subsystems/aerodynamics/aerodynamics_builder.py, aviary/subsystems/test/test_premission.py
This fixes 2 failures from the nightly build:
1. OpenMDAO error message for `get_val` has recently changed. Make test work with both.
2. The 2dof aero was missing some promotes that formerly had non-zero default values.  This fixes the broken GwGm test and bench, which now optimizes to a nice 0,1 in 21 iters.
- Resolves #
None
None
=> Fixed a couple of regressions on the nightly build.

aviary/interface/reports.py, aviary/subsystems/mass/gasp_based/test/test_mass_summation.py, aviary/subsystems/propulsion/test/test_custom_engine_model.py, aviary/subsystems/propulsion/test/test_turboprop_model.py, aviary/utils/functions.py
Fixes some failing test on the nightly that are related to the following:
1. OpenMDAO system data structures storing prom<->abs name resolutions have been removed and replaced with a new _resolver object.
2. The remaining support for hybrid variable names has been removed from OpenMDAO.
Summary of PR.
- Resolves #
None
None
=> Some fixes for the latest changes in OpenMDAO 3.38.1-dev

aviary/visualization/dashboard.py
This PR fixes an error with the dashboard.py file caused by an OpenMDAO update to remove support for hybrid pathnames.
Formal issue never created...
> aviary run_mission 'aviary/models/test_aircraft/aircraft_for_bench_FwFm.csv'
> aviary dashboard aircraft_for_bench_FwFm
results in this error:
after the change the above test runs without error.
Presumably if people are running an old version of OpenMDAO then this will break their dashboards.
Latest OpenMDAO after the hybrid pathnames change - I don't know exactly which version this was, but I tested this fix with these versions of aviary/openmdao:
> python -m openmdao --version
>aviary --version
=> Update to dashboard to fix error caused by OpenMDAO update

aviary/validation_cases/benchmark_tests/test_bench_FwGm.py
Fix one more failing bench due to removal of hybrid paths in OpenMDAO.
Missed this one in my last PR.
- Resolves #
None
None
=> Fix one more failing bench due to removal of hybrid paths in OpenMDAO.

.github/workflows/test_workflow_no_dev_install.yml
Updated the `no_dev_install` workflow to use the specified run_name if one is given (e.g. when triggered by a release)
- Resolves #
None
None
=> Updated the `no_dev_install` workflow to use the specified run_name if one is given

aviary/subsystems/aerodynamics/aerodynamics_builder.py
The deepcopy isn't needed, and it breaks some external builders.
- Resolves #794
None
None
=> Remove deepcopy from aero builder.

aviary/docs/user_guide/reserve_missions.ipynb, aviary/interface/methods_for_level2.py, aviary/interface/test/test_phase_info.py, aviary/interface/test/test_reserve_support.py, aviary/mission/height_energy_problem_configurator.py, aviary/mission/two_dof_problem_configurator.py
1. Fix for a regression that came in with the phase_info revamp, where time_duration (formerly target_duration) was no longer being respected.
2. Print a warning if both time_duration and a duration initial guess are specified.
3. Clean up the arguments being passed into set_time_options to avoid dymos warnings.
- Resolves #805 
None
None
=> Fix for bug where time duration value was no longer respected.

aviary/utils/utils.py
- Fixes bug where arrays of dimension 3 or higher always fail the type checking when adding a hierarchy variable to AviaryValues
- Updated some comments to 100-line length while I was in `utils.py`
- Resolves #
None
None
=> Bugfix for higher dimensional arrays in AviaryValues object

aviary/visualization/dashboard.py
In the optimization history code, there was some javascript code being created using an f-string and it didn't make use of double braces needed to create a literal brace. 
Also, unrelated to the issue, there was a bug in the aviary variables tab creation because the serialization of the aviary metadata failed. Need to make use of the `make_serializable` function from OpenMDAO to clean that up.
- Resolves #685 
None
None
=> Fixed smalll bugs in aviary dashboard optimization history and aviary variables tabs

aviary/subsystems/mass/flops_based/wing_detailed.py
Address a numpy deprecation warning about assigning a vector to a single vector index.
- Resolves #
None
None
=> Address a numpy deprecation warning about assigning a vector to a single vector index.

aviary/validation_cases/benchmark_tests/test_bench_multiengine.py
Since the throttle in descent should generally be around 0, the throttle_allocation between the 2 engines probably has very little effect on the fuel objective, so we should really just assert the climb and cruise phases.
Summary of PR.
- Resolves #
None
None
=> Fix occasional failure of multi engine test due to insensitivity of objective to throttle allocation in descent.

.github/actions/prepare_environment/action.yml
build_pyoptsparse started giving us an older version of IPOPT. Not sure why, but we seem to be able to update it in the next step of the build script.
Summary of PR.
- Resolves #
None
None
=> Fix for IPOPT CI failures.

aviary/interface/cmd_entry_points.py
When `aviary` was called at the command line without any logs, the code was calling it again via a system call, making it longer. Better way is to put the '-h' in the args.
- Resolves #
None
None
=> Speedup for aviary cmd-line: avoid double-call when called with no args.
